#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

case "${COMPONENT}" in
    rpm)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "rpm-${VERSION}-release" \
                https://github.com/rpm-software-management/rpm.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    popt)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "popt-${VERSION}-release" \
                https://github.com/rpm-software-management/popt.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    libarchive)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "v${VERSION}" \
                https://github.com/libarchive/libarchive.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    lua)
        # Lua uses tarball downloads from official site
        TARBALL="/tmp/lua-${VERSION}.tar.gz"
        retry_with_backoff "${TARBALL}" \
            wget -O "${TARBALL}" "https://www.lua.org/ftp/lua-${VERSION}.tar.gz"
        tar xf "${TARBALL}" -C "${SOURCE_DIR}" --strip-components=1
        rm "${TARBALL}"
        ;;

    zlib)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "v${VERSION}" \
                https://github.com/madler/zlib.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    xz)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "v${VERSION}" \
                https://github.com/tukaani-project/xz.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    zstd)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "v${VERSION}" \
                https://github.com/facebook/zstd.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    openssl)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "openssl-${VERSION}" \
                https://github.com/openssl/openssl.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    file)
        # file/libmagic - uses FILE<major>_<minor> tag format
        VERSION_UNDERSCORES="${VERSION//./_}"
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "FILE${VERSION_UNDERSCORES}" \
                https://github.com/file/file.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    sqlite)
        # SQLite uses a numeric version (e.g., 3510300) with a year-based URL.
        # Try the current year first, then fall back to previous years.
        TARBALL="/tmp/sqlite-autoconf-${VERSION}.tar.gz"
        CURRENT_YEAR=$(date +%Y)
        SQLITE_URL=""
        for YEAR in $(seq "${CURRENT_YEAR}" -1 2020); do
            URL="https://www.sqlite.org/${YEAR}/sqlite-autoconf-${VERSION}.tar.gz"
            if wget --spider "${URL}" 2>/dev/null; then
                SQLITE_URL="${URL}"
                break
            fi
        done
        if [ -z "${SQLITE_URL}" ]; then
            echo "ERROR: Could not find sqlite-autoconf-${VERSION}.tar.gz on sqlite.org"
            exit 1
        fi
        retry_with_backoff "${TARBALL}" \
            wget -O "${TARBALL}" "${SQLITE_URL}"
        tar xf "${TARBALL}" -C "${SOURCE_DIR}" --strip-components=1
        rm "${TARBALL}"
        ;;

    bzip2)
        retry_with_backoff "${SOURCE_DIR}" \
            git clone --depth 1 \
                --branch "bzip2-${VERSION}" \
                https://gitlab.com/bzip2/bzip2.git "${SOURCE_DIR}"
        rm -rf "${SOURCE_DIR}/.git"
        ;;

    *)
        echo "ERROR: Unknown component '${COMPONENT}'"
        echo "Valid components: rpm, popt, libarchive, lua, zlib, xz, zstd, openssl, file, sqlite, bzip2"
        exit 1
        ;;
esac
