#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

sudo apt update
DEBIAN_FRONTEND=noninteractive sudo apt install -y \
    autoconf \
    automake \
    autopoint \
    build-essential \
    cmake \
    gettext \
    git \
    libtool \
    pkg-config \
    rsync \
    scdoc \
    wget
